### ISSUE TITLE
How to pass -quiet option?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [Izhaki/nodemon-webpack-plugin#123] opened 2020-08-16 01:04 UTC
How to pass -quiet option?

not working:
![image](https://user-images.githubusercontent.com/69426460/90324313-c8b9aa00-df75-11ea-8782-575251719f69.png)

**Comment by Izhaki** [comment] 2020-08-16 17:37
Did you try:

```js
new NodemonPlugin({
  quiet: true,    
});
```

**Comment by MaxmaxmaximusAWS** [comment] 2020-08-17 01:12
@Izhaki no, this is missing in your documentation and in the link you give to the "configuration object".

![image](https://user-images.githubusercontent.com/69426460/90348682-befc7900-e03f-11ea-9f17-378dc646da11.png)

![image](https://user-images.githubusercontent.com/69426460/90348688-c58af080-e03f-11ea-8763-9db58baff3ef.png)

![image](https://user-images.githubusercontent.com/69426460/90348705-d0458580-e03f-11ea-97dc-e07bc23ba663.png)

I think this is a problem in the documentation. =)

**Comment by Izhaki** [comment] 2020-08-17 07:55
Duplicate of https://github.com/Izhaki/nodemon-webpack-plugin/issues/89

**Comment by Izhaki** [comment] 2020-08-17 08:08
This is indeed a documentation issue.

Thing is, as the plugin simply uses the API of `nodemon`, it makes little sense to document it here - it should be documented in the `nodemon` repo, and I opened [an issue there instead](https://github.com/remy/nodemon/issues/1753).

Feel free to contribute there.

**Closed by Izhaki** 2020-08-17 08:08 UTC
Labels: question
